apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "#GOOGLE_PROJECT_ID#-cert-issuer"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "#LETSENCRYPT_EMAIL#"
    privateKeySecretRef:
      name: cert-manager-private-key
    solvers:
      - http01:
          ingress:
            name: "#GOOGLE_PROJECT_ID#-ingress"
